 - Q: "What is the current capital of Japan?"
   A: "Tokyo"

 - Q: "What is the snow monkey, also called Japanese macaque, known for?"
   A: "It is the northernmost primate on Earth."

 - Q: "Which quarter in Tokyo is known for the colorful and vibrant street fashion?"
   A: "Toneri"

 - Q: "What is the largest and most populous island in Japan?"
   A: "Honshu"

 - Q: "What is the traditional dress of Japan?"
   A: "Kimono"

 - Q: "What of the following forms of martial arts does not originate from Japan?"
   A: "Taekwondo"

 - Q: "Which sacred animal can you find wandering in the Nara Park?"
   A: "Deer"

 - Q: "What is the symbol of Shinto, the indigenous religion in Japan?"
   A: "A gate"

 - Q: "Fuji is a sacred symbol of Japan. What is it actually?"
   A: "A mountain"

 - Q: "When was the last time when Mount Fuji erupted?"
   A: "In 1707"

 - Q: "The Shinkansen is the network of high-speed railway lines in Japan. The design of the bullet trains running on this network was inspired by which animal?"
   A: "Kingfishers"

 - Q: "Which of the following is not a typical Japanese dish?"
   A: "Kimchi"

 - Q: "What do waiters or waitresses say to welcome guests in Japanese restaurants?"
   A: "Irasshaimase"

 - Q: "What does Sushi mean in Japanese?"
   A: "Sour rice"

 - Q: "What does a Geisha do?"
   A: "To perform traditional Japanese songs and dance"

 - Q: "The U.S dropped two atomic bombs on which Japanese cities during World War II?"
   A: "Hiroshima and Nagasaki"

 - Q: "The Obon festival, one of the major holiday seasons in Japan, takes place during which season of the year?"
   A: "Summer"

 - Q: "Which Emperor decided to move the capital of Japan to Tokyo from Kyoto?"
   A: "Emperor Meiji"

 - Q: "Since the end of World War II, which was the first country that Japan send the military forces?"
   A: "Iraq"

 - Q: "When will Japan host the Summer Olympic Games for the second time?"
   A: "2021"
